version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: false
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: /JTSqQ0h6C+JY5+gZGSkx6BoZB0kjwTrSrvpjKQ72tKFhsKdRbQahj9fw4zy/vEE
  on:
    branch: master
