version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - main
nuget:  
  disable_publish_on_pr: true
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: /JTSqQ0h6C+JY5+gZGSkx6BoZB0kjwTrSrvpjKQ72tKFhsKdRbQahj9fw4zy/vEE
  on:
    branch: main
